# Corrección CLAVE: TODAS las strings complejas deben llevar comillas dobles (")
API_URL = "http://localhost:5000/api"
MAPBOX_TOKEN = "sk.eyJ1IjoiZHZpZ29jMjgiLCJhIjoiY21oYTJrODN0MHNvNzJrcHZja3NmOGhvYyJ9.NwZ5N-T_MOhSaRZHQra1YA"

# Configuración de Supabase (para la API)
SUPABASE_URL = "https://tvgtrknztiflqqxdlbqz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2Z3Rya256dGlmbHFxeGRsYnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODYxMTksImV4cCI6MjA3NzE2MjExOX0.vkzWyOrVWLS1ysb6cECC2rce4i-sa7OSK-tHpAhxegA"

# Configuración de Gemini AI
GEMINI_API_KEY = "AIzaSyA3OFytbc5gTRT-F-4ako6D1NvLJEdkkwA"